# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/enes/Desktop/PhD/Communication/pointCloud_sender

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/enes/Desktop/PhD/Communication/pointCloud_sender/build

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/enes/Desktop/PhD/Communication/pointCloud_sender/build/CMakeFiles /home/enes/Desktop/PhD/Communication/pointCloud_sender/build//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/enes/Desktop/PhD/Communication/pointCloud_sender/build/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named VoxelGrid

# Build rule for target.
VoxelGrid: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 VoxelGrid
.PHONY : VoxelGrid

# fast build rule for target.
VoxelGrid/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VoxelGrid.dir/build.make CMakeFiles/VoxelGrid.dir/build
.PHONY : VoxelGrid/fast

#=============================================================================
# Target rules for targets named OBPointCloud

# Build rule for target.
OBPointCloud: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 OBPointCloud
.PHONY : OBPointCloud

# fast build rule for target.
OBPointCloud/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OBPointCloud.dir/build.make CMakeFiles/OBPointCloud.dir/build
.PHONY : OBPointCloud/fast

#=============================================================================
# Target rules for targets named server

# Build rule for target.
server: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 server
.PHONY : server

# fast build rule for target.
server/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/build
.PHONY : server/fast

src/PointCloud.o: src/PointCloud.cpp.o
.PHONY : src/PointCloud.o

# target to build an object file
src/PointCloud.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OBPointCloud.dir/build.make CMakeFiles/OBPointCloud.dir/src/PointCloud.cpp.o
.PHONY : src/PointCloud.cpp.o

src/PointCloud.i: src/PointCloud.cpp.i
.PHONY : src/PointCloud.i

# target to preprocess a source file
src/PointCloud.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OBPointCloud.dir/build.make CMakeFiles/OBPointCloud.dir/src/PointCloud.cpp.i
.PHONY : src/PointCloud.cpp.i

src/PointCloud.s: src/PointCloud.cpp.s
.PHONY : src/PointCloud.s

# target to generate assembly for a file
src/PointCloud.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OBPointCloud.dir/build.make CMakeFiles/OBPointCloud.dir/src/PointCloud.cpp.s
.PHONY : src/PointCloud.cpp.s

src/funcs.o: src/funcs.cpp.o
.PHONY : src/funcs.o

# target to build an object file
src/funcs.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OBPointCloud.dir/build.make CMakeFiles/OBPointCloud.dir/src/funcs.cpp.o
.PHONY : src/funcs.cpp.o

src/funcs.i: src/funcs.cpp.i
.PHONY : src/funcs.i

# target to preprocess a source file
src/funcs.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OBPointCloud.dir/build.make CMakeFiles/OBPointCloud.dir/src/funcs.cpp.i
.PHONY : src/funcs.cpp.i

src/funcs.s: src/funcs.cpp.s
.PHONY : src/funcs.s

# target to generate assembly for a file
src/funcs.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OBPointCloud.dir/build.make CMakeFiles/OBPointCloud.dir/src/funcs.cpp.s
.PHONY : src/funcs.cpp.s

src/pointCloud_utils.o: src/pointCloud_utils.cpp.o
.PHONY : src/pointCloud_utils.o

# target to build an object file
src/pointCloud_utils.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OBPointCloud.dir/build.make CMakeFiles/OBPointCloud.dir/src/pointCloud_utils.cpp.o
.PHONY : src/pointCloud_utils.cpp.o

src/pointCloud_utils.i: src/pointCloud_utils.cpp.i
.PHONY : src/pointCloud_utils.i

# target to preprocess a source file
src/pointCloud_utils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OBPointCloud.dir/build.make CMakeFiles/OBPointCloud.dir/src/pointCloud_utils.cpp.i
.PHONY : src/pointCloud_utils.cpp.i

src/pointCloud_utils.s: src/pointCloud_utils.cpp.s
.PHONY : src/pointCloud_utils.s

# target to generate assembly for a file
src/pointCloud_utils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OBPointCloud.dir/build.make CMakeFiles/OBPointCloud.dir/src/pointCloud_utils.cpp.s
.PHONY : src/pointCloud_utils.cpp.s

src/server.o: src/server.cpp.o
.PHONY : src/server.o

# target to build an object file
src/server.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server.cpp.o
.PHONY : src/server.cpp.o

src/server.i: src/server.cpp.i
.PHONY : src/server.i

# target to preprocess a source file
src/server.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server.cpp.i
.PHONY : src/server.cpp.i

src/server.s: src/server.cpp.s
.PHONY : src/server.s

# target to generate assembly for a file
src/server.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server.cpp.s
.PHONY : src/server.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... OBPointCloud"
	@echo "... VoxelGrid"
	@echo "... server"
	@echo "... src/PointCloud.o"
	@echo "... src/PointCloud.i"
	@echo "... src/PointCloud.s"
	@echo "... src/funcs.o"
	@echo "... src/funcs.i"
	@echo "... src/funcs.s"
	@echo "... src/pointCloud_utils.o"
	@echo "... src/pointCloud_utils.i"
	@echo "... src/pointCloud_utils.s"
	@echo "... src/server.o"
	@echo "... src/server.i"
	@echo "... src/server.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

